/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pantallas;

import dtos.ComandaDTO;
import entidades.Pago;
import fachada.PagoFachada;
import interfaz.IGestionPagos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author valeria
 */
public class DlgPagoComanda extends javax.swing.JDialog {
    private float total;
    private float restante;
    private final List<Pago> pagosHechos = new ArrayList<>();
    private final IGestionPagos pagoFachada;
    private final ComandaDTO comanda;

    /**
     * Creates new form DlgPagoComanda
     */
    public DlgPagoComanda(java.awt.Frame parent, boolean modal, ComandaDTO comanda) {
        super(parent, modal);
        initComponents();
        
        this.total = comanda.getTotal();
        this.restante = total;
        
        this.comanda = comanda;
        this.pagoFachada = new PagoFachada();

        btnFinalizar.setVisible(false);

        pnlPedidos.setLayout(new BoxLayout(pnlPedidos, BoxLayout.Y_AXIS));
        pnlPagosHechos.setLayout(new BoxLayout(pnlPagosHechos, BoxLayout.Y_AXIS));

        cargarTicketComanda(comanda);
        actualizarRestante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTicket = new javax.swing.JPanel();
        lblTituloTicket = new javax.swing.JLabel();
        lblMesaCliente = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        lblNombreCliente = new javax.swing.JLabel();
        scrlPedidos = new javax.swing.JScrollPane();
        pnlPedidos = new javax.swing.JPanel();
        separator2 = new javax.swing.JSeparator();
        lblTotalPagarCliente = new javax.swing.JLabel();
        separator3 = new javax.swing.JSeparator();
        lblMetodosPago = new javax.swing.JLabel();
        btnMetodoEfectivo = new javax.swing.JButton();
        btnMetodoTarjeta = new javax.swing.JButton();
        btnMetodoCodi = new javax.swing.JButton();
        separator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPagosHechos = new javax.swing.JPanel();
        btnFinalizar = new javax.swing.JButton();
        lblAtras = new javax.swing.JLabel();
        lblRestantePagar = new javax.swing.JLabel();
        separator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTicket.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloTicket.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblTituloTicket.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloTicket.setText("Pago por Comanda");

        lblMesaCliente.setFont(new java.awt.Font("Telugu Sangam MN", 1, 22)); // NOI18N
        lblMesaCliente.setText("Mesa X - Cliente X");

        lblNombreCliente.setFont(new java.awt.Font("Telugu Sangam MN", 1, 14)); // NOI18N
        lblNombreCliente.setText("Cliente X");

        pnlPedidos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPedidosLayout = new javax.swing.GroupLayout(pnlPedidos);
        pnlPedidos.setLayout(pnlPedidosLayout);
        pnlPedidosLayout.setHorizontalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        pnlPedidosLayout.setVerticalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        scrlPedidos.setViewportView(pnlPedidos);

        lblTotalPagarCliente.setFont(new java.awt.Font("Telugu Sangam MN", 1, 14)); // NOI18N
        lblTotalPagarCliente.setText("Total Cliente X: $XXX.XXX ");

        lblMetodosPago.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        lblMetodosPago.setForeground(new java.awt.Color(153, 153, 153));
        lblMetodosPago.setText("Métodos de Pago");

        btnMetodoEfectivo.setBackground(new java.awt.Color(204, 204, 204));
        btnMetodoEfectivo.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnMetodoEfectivo.setText("EFECTIVO");
        btnMetodoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoEfectivoActionPerformed(evt);
            }
        });

        btnMetodoTarjeta.setBackground(new java.awt.Color(204, 204, 204));
        btnMetodoTarjeta.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnMetodoTarjeta.setText("TARJETA");

        btnMetodoCodi.setBackground(new java.awt.Color(204, 204, 204));
        btnMetodoCodi.setFont(new java.awt.Font("Telugu Sangam MN", 1, 13)); // NOI18N
        btnMetodoCodi.setText("CoDi");

        pnlPagosHechos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPagosHechosLayout = new javax.swing.GroupLayout(pnlPagosHechos);
        pnlPagosHechos.setLayout(pnlPagosHechosLayout);
        pnlPagosHechosLayout.setHorizontalGroup(
            pnlPagosHechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        pnlPagosHechosLayout.setVerticalGroup(
            pnlPagosHechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlPagosHechos);

        btnFinalizar.setBackground(new java.awt.Color(232, 215, 38));
        btnFinalizar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(102, 102, 0));
        btnFinalizar.setText("FINALIZAR");

        lblAtras.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        lblAtras.setText("X");

        lblRestantePagar.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblRestantePagar.setText("Restante a Pagar: $XXX.XXX");

        javax.swing.GroupLayout pnlTicketLayout = new javax.swing.GroupLayout(pnlTicket);
        pnlTicket.setLayout(pnlTicketLayout);
        pnlTicketLayout.setHorizontalGroup(
            pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTicketLayout.createSequentialGroup()
                .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlTicketLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTicketLayout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotalPagarCliente)
                                .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreCliente)
                                    .addComponent(scrlPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlTicketLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRestantePagar)
                            .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlTicketLayout.createSequentialGroup()
                                    .addComponent(lblMetodosPago)
                                    .addGap(100, 100, 100))
                                .addComponent(separator3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTicketLayout.createSequentialGroup()
                                    .addComponent(btnMetodoEfectivo)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMetodoTarjeta)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMetodoCodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(separator4)
                                .addComponent(jScrollPane1)
                                .addComponent(separator5, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketLayout.createSequentialGroup()
                        .addComponent(lblTituloTicket)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketLayout.createSequentialGroup()
                        .addComponent(lblMesaCliente)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketLayout.createSequentialGroup()
                        .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketLayout.createSequentialGroup()
                        .addComponent(lblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketLayout.createSequentialGroup()
                        .addComponent(btnFinalizar)
                        .addGap(20, 20, 20))))
        );
        pnlTicketLayout.setVerticalGroup(
            pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTicketLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloTicket)
                .addGap(18, 18, 18)
                .addComponent(lblMesaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPagarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMetodosPago)
                .addGap(18, 18, 18)
                .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetodoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetodoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetodoCodi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(lblRestantePagar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMetodoEfectivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMetodoCodi;
    private javax.swing.JButton btnMetodoEfectivo;
    private javax.swing.JButton btnMetodoTarjeta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblMesaCliente;
    private javax.swing.JLabel lblMetodosPago;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblRestantePagar;
    private javax.swing.JLabel lblTituloTicket;
    private javax.swing.JLabel lblTotalPagarCliente;
    private javax.swing.JPanel pnlPagosHechos;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JPanel pnlTicket;
    private javax.swing.JScrollPane scrlPedidos;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JSeparator separator4;
    private javax.swing.JSeparator separator5;
    // End of variables declaration//GEN-END:variables

    private void cargarTicketComanda(ComandaDTO comanda) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void actualizarRestante() {
        lblRestantePagar.setText("Restante a pagar: $" + restante);

        btnFinalizar.setVisible(restante == 0);

        btnMetodoEfectivo.setEnabled(restante > 0);
        btnMetodoTarjeta.setEnabled(restante > 0);
        btnMetodoCodi.setEnabled(restante > 0);
    }
}
