package pantallas;

import BO.ComandaBO;
import coordinador.CoordinadorInterfaces;
import dto.PedidoNuevoDTO;
import dto.ComandaDTO;
import java.time.LocalDate;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Piña
 */
public class DlgResumenComanda extends javax.swing.JDialog {

    private Integer numMesa;
    private String nombreCliente;
    private List<PedidoNuevoDTO> productos;
    private CoordinadorInterfaces coordinador;

    /**
     * Creates new form DlgResumenComanda
     */
    public DlgResumenComanda(CoordinadorInterfaces coordinador, java.awt.Frame parent, List<PedidoNuevoDTO> productos, Integer numMesa, String nombreCliente) {
        super(parent, true);
        this.coordinador = coordinador;
        initComponents();
        this.productos = productos;
        this.numMesa = numMesa;
        this.nombreCliente = nombreCliente;

        configurarListaPedidos(productos);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreMesa = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        pnlListaProductos = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 235));

        jPanel1.setBackground(new java.awt.Color(255, 248, 235));

        lblNombreMesa.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblNombreMesa.setForeground(new java.awt.Color(153, 102, 0));
        lblNombreMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreMesa.setText("Mesa x");

        lblNombreCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(153, 102, 0));
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setText("Resumen comanda x");

        pnlListaProductos.setBackground(new java.awt.Color(255, 248, 235));
        pnlListaProductos.setFont(new java.awt.Font("Muna", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlListaProductosLayout = new javax.swing.GroupLayout(pnlListaProductos);
        pnlListaProductos.setLayout(pnlListaProductosLayout);
        pnlListaProductosLayout.setHorizontalGroup(
            pnlListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlListaProductosLayout.setVerticalGroup(
            pnlListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(pnlListaProductos);

        btnConfirmar.setBackground(new java.awt.Color(44, 44, 44));
        btnConfirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNombreMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNombreMesa)
                .addGap(26, 26, 26)
                .addComponent(lblNombreCliente)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed


    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        if (productos == null || productos.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debes agregar al menos un producto para crear la comanda",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        coordinador.enviarComandaAFinal(nombreCliente, numMesa, productos);
        this.dispose();
    }//GEN-LAST:event_btnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreMesa;
    private javax.swing.JPanel pnlListaProductos;
    // End of variables declaration//GEN-END:variables

    public void setMesaAndCliente(Integer numMesa, String cliente) {

        lblNombreMesa.setText("Mesa " + numMesa);
        lblNombreCliente.setText("Resumen comanda: " + cliente);
    }

    private void configurarListaPedidos(List<PedidoNuevoDTO> comandaTemporal) {
        productos = comandaTemporal;
        pnlListaProductos.setLayout(new javax.swing.BoxLayout(pnlListaProductos, javax.swing.BoxLayout.Y_AXIS));
        pnlListaProductos.removeAll();

        jScrollPane.getViewport().setBackground(new java.awt.Color(255, 248, 235));

        java.util.Map<String, Integer> agrupador = new java.util.HashMap<>();
        for (PedidoNuevoDTO ped : comandaTemporal) {
            String detalle = ped.toString();
            agrupador.put(detalle, agrupador.getOrDefault(detalle, 0) + 1);
        }

        for (java.util.Map.Entry<String, Integer> entry : agrupador.entrySet()) {
            String textoAgrupado = entry.getValue() + " x " + entry.getKey();

            javax.swing.JLabel lblPedido = new javax.swing.JLabel(textoAgrupado);

            lblPedido.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            lblPedido.setFont(new java.awt.Font("Trebuchet MS", java.awt.Font.PLAIN, 14));
            lblPedido.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

            pnlListaProductos.add(lblPedido);
        }

        pnlListaProductos.revalidate();
        pnlListaProductos.repaint();
    }
}
