/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import coordinador.CoordinadorInterfaces;
import dto.ComandaDTO;
import dto.MesaDTO;
import dto.PedidoNuevoDTO;
import fachada.MesaFachada;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Home
 */
public class FrmPantallaComandas extends javax.swing.JFrame {

    private coordinador.CoordinadorInterfaces coordinador;
    int idMesero = 1;

    MesaFachada fachada = new MesaFachada();

    /**
     * Creates new form FrmPantallaComandas
     *
     * @param coordinador
     */
    public FrmPantallaComandas(CoordinadorInterfaces coordinador) {
        this.coordinador = coordinador;
        initComponents();
        this.setLocationRelativeTo(null);
        panMesas.setLayout(new BoxLayout(panMesas, BoxLayout.Y_AXIS));
        cargarMesas();
        panComandas.revalidate();
        panComandas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panComandas = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        btnLevantarComanda = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panMesas = new javax.swing.JPanel();
        lblSeleccioneMesa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panTituloMesas = new javax.swing.JPanel();
        lblMesas1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panComandas.setBackground(new java.awt.Color(255, 255, 255));

        panHeader.setBackground(new java.awt.Color(255, 202, 102));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_header.png"))); // NOI18N

        lblEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("Empleado X");

        btnLevantarComanda.setBackground(new java.awt.Color(255, 227, 172));
        btnLevantarComanda.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLevantarComanda.setText("Levantar Comanda");
        btnLevantarComanda.setBorder(null);
        btnLevantarComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLevantarComandaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLevantarComandaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLevantarComandaMouseReleased(evt);
            }
        });
        btnLevantarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantarComandaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(213, 210, 203));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton2.setText("Cerrar Sesión");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLevantarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeaderLayout.createSequentialGroup()
                        .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpleado)
                            .addComponent(btnLevantarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panMesas.setLayout(new javax.swing.BoxLayout(panMesas, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panMesas);

        lblSeleccioneMesa.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblSeleccioneMesa.setForeground(new java.awt.Color(204, 204, 204));
        lblSeleccioneMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccioneMesa.setText("Seleccione una mesa");

        lblMesas1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMesas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesas1.setText("MESAS");

        javax.swing.GroupLayout panTituloMesasLayout = new javax.swing.GroupLayout(panTituloMesas);
        panTituloMesas.setLayout(panTituloMesasLayout);
        panTituloMesasLayout.setHorizontalGroup(
            panTituloMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTituloMesasLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblMesas1)
                .addGap(52, 52, 52))
        );
        panTituloMesasLayout.setVerticalGroup(
            panTituloMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloMesasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMesas1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panComandasLayout = new javax.swing.GroupLayout(panComandas);
        panComandas.setLayout(panComandasLayout);
        panComandasLayout.setHorizontalGroup(
            panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panComandasLayout.createSequentialGroup()
                .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panComandasLayout.createSequentialGroup()
                        .addContainerGap(160, Short.MAX_VALUE)
                        .addComponent(lblSeleccioneMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(panComandasLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(panTituloMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panComandasLayout.setVerticalGroup(
            panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComandasLayout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panComandasLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lblSeleccioneMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComandasLayout.createSequentialGroup()
                        .addComponent(panTituloMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jScrollPane2.setViewportView(panComandas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLevantarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLevantarComandaActionPerformed

    private void btnLevantarComandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLevantarComandaMousePressed

        btnLevantarComanda.setFocusPainted(false);
        btnLevantarComanda.setContentAreaFilled(false);
        btnLevantarComanda.setOpaque(true);

        btnLevantarComanda.setBackground(Color.decode("#F3AE29"));
        btnLevantarComanda.setBorder(BorderFactory.createLineBorder(Color.decode("#C79A42"), 2));
    }//GEN-LAST:event_btnLevantarComandaMousePressed

    private void btnLevantarComandaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLevantarComandaMouseReleased
        btnLevantarComanda.setBackground(Color.decode("#FFE3AC"));
        btnLevantarComanda.setBorder(null);
    }//GEN-LAST:event_btnLevantarComandaMouseReleased

    private void btnLevantarComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLevantarComandaMouseClicked
        if (mesaSeleccionada != null) {
            coordinador.mostrarRegistrarCliente(mesaSeleccionada);
        } else {
            System.out.println("Selecciona una mesa primero");
        }

        this.dispose();
    }//GEN-LAST:event_btnLevantarComandaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaComandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaComandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaComandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaComandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                coordinador.CoordinadorInterfaces coordinador = new coordinador.CoordinadorInterfaces();
                new FrmPantallaComandas(coordinador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLevantarComanda;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblMesas1;
    private javax.swing.JLabel lblSeleccioneMesa;
    private javax.swing.JPanel panComandas;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panMesas;
    private javax.swing.JPanel panTituloMesas;
    // End of variables declaration//GEN-END:variables
    private JButton btnSeleccionado = null;
    private MesaDTO mesaSeleccionada = null;

    public void cargarMesas() {
        panMesas.removeAll();
        btnLevantarComanda.setVisible(false);

        List<MesaDTO> mesas = fachada.obtenerMesasPorMesero(idMesero);

        for (MesaDTO mesa : mesas) {
            JButton btn = new JButton("Mesa " + mesa.getNumeroMesa());

            btn.setAlignmentX(Component.CENTER_ALIGNMENT);
            btn.setMaximumSize(new Dimension(150, 60));

            btn.setFocusPainted(false);

            btn.addActionListener(e -> {

                panComandas.remove(lblSeleccioneMesa);
                btnLevantarComanda.setVisible(true);
                panComandas.revalidate();
                panComandas.repaint();

                if (btnSeleccionado != null) {

                    btnSeleccionado.setBackground(Color.decode("#FFE3AC"));
                    btnSeleccionado.setFont(new Font("Arial", Font.PLAIN, 18));
                    btnSeleccionado.setBorder(null);
                }

                btn.setBackground(Color.decode("#FFD481"));
                btn.setFont(new Font("Arial", Font.BOLD, 18));
                btn.setBorder(BorderFactory.createLineBorder(Color.decode("#FFBE41"), 2));

                btnSeleccionado = btn;
                mesaSeleccionada = mesa;

                System.out.println("Seleccionaste Mesa " + mesa);
            });

            btn.setBackground(Color.decode("#FFE3AC"));
            btn.setFont(new Font("Arial", Font.PLAIN, 18));
            btn.setBorder(null);

            panMesas.add(btn);
            panMesas.add(Box.createVerticalStrut(28));
        }

        panMesas.revalidate();
        panMesas.repaint();
    }
    private JPanel contenedorComandas;

    public void añadirNuevaComanda(ComandaDTO comanda) {
        ComandaCard card = new ComandaCard(comanda);
        this.panComandas.add(card);

        this.panComandas.revalidate();
        this.panComandas.repaint();
    }

    public class ComandaCard extends JPanel {

        public ComandaCard(ComandaDTO comanda) {
            setLayout(new BorderLayout());
            setBorder(new javax.swing.border.LineBorder(Color.ORANGE, 2, true));
            setBackground(new Color(255, 235, 205));

            JLabel lblTitulo = new JLabel(comanda.getNombreCliente().toUpperCase() + ": PENDIENTE");
            lblTitulo.setFont(new Font("Arial", Font.BOLD, 14));
            lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
            add(lblTitulo, BorderLayout.NORTH);

            StringBuilder sb = new StringBuilder();
            int contador = 1;
            for (PedidoNuevoDTO ped : comanda.getListaPedidos()) {
                sb.append("Pedido ").append(contador).append(": ")
                        .append(ped.toString())
                        .append("\n");
                contador++;
            }

            JTextArea txtPedidos = new JTextArea(sb.toString());
            txtPedidos.setEditable(false);
            txtPedidos.setOpaque(false);
            txtPedidos.setFont(new Font("Monospaced", Font.PLAIN, 12));
            txtPedidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
            add(txtPedidos, BorderLayout.CENTER);

            JPanel pnlBotones = new JPanel();
            pnlBotones.setOpaque(false);
            pnlBotones.setLayout(new FlowLayout(FlowLayout.RIGHT));
            JButton btnAgregar = new JButton("Agregar");
            JButton btnCancelar = new JButton("Cancelar");

            btnCancelar.setBackground(new Color(255, 153, 153));
            btnAgregar.setBackground(new Color(255, 204, 102));

            pnlBotones.add(btnAgregar);
            pnlBotones.add(btnCancelar);
            add(pnlBotones, BorderLayout.SOUTH);
        }
    }

}
